<?php if($this->getCurrencyCount() > 1): ?>
  <?php $currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();
 ?>
  <span><?php echo $this->__('Currency :') ?>
    <span><?php echo $currency_symbol ?></span>
  </span>
  <ul id="custom-currency-selector" class="topbar-dropdown">
    <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
      <li>
        <span><?php echo $currency_code ?></span>
        <a href="<?php echo $this->getSwitchCurrencyUrl($_code)?>">
            <?php echo $_code ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
